import './globals.css'
import Header from "@/components/ui/header/Header";
import NavBar from "@/components/ui/navbar/NavBar";


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={"flex flex-col h-screen bg-grey-100 dark:bg-black-100"}>
        <Header/>
            {children}
            <NavBar/>
        </body>
        </html>
    )
}
